// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJYeBGyr9ttVRsQDltMagKp4KCAACJUzY',
    appId: '1:283959765747:web:03c791b269ccc153a66586',
    messagingSenderId: '283959765747',
    projectId: 'chat-app-564af',
    authDomain: 'chat-app-564af.firebaseapp.com',
    storageBucket: 'chat-app-564af.appspot.com',
    measurementId: 'G-ZVYQ1T8YQP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBONS9MRCPZYcppBx7BRlGKk1mpFtMU1o',
    appId: '1:283959765747:android:b0a9231823b3d8e6a66586',
    messagingSenderId: '283959765747',
    projectId: 'chat-app-564af',
    storageBucket: 'chat-app-564af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr05KCWf8nffwbzgX7_n0qQhgJ4LmR83M',
    appId: '1:283959765747:ios:620dc104d37e574ca66586',
    messagingSenderId: '283959765747',
    projectId: 'chat-app-564af',
    storageBucket: 'chat-app-564af.appspot.com',
    iosClientId: '283959765747-rhlr4jc4p78lknua0pa1nnnnvhlmm8pf.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
